### ISSUE TITLE
iOS icons: Transparency for Dark Palette?

### ISSUE THREAD

**Issue by papernapkinhead** [deaghean/omnifocus-perspective-icons#4]
First off—thanks so much for this icon set! I've been enjoying it for some time now.

With a dark palette in TestFlight, it'd look super sharp if the white portion of the iOS icons were transparent (like the default icons) so the dark tint can bleed through.

A few of your icons alongside one of the default icons:
![screenshot](https://cloud.githubusercontent.com/assets/589409/8073175/440bf8c8-0ed6-11e5-8bb5-3ae17a8ea2f8.png)

Thanks for the consideration!

**Comment by deaghean** [comment]
I considered that. With the previous TestFlight build, I actually suggested flipping the white to black for the dark mode (https://twitter.com/deaghean/status/606650556640133120), and had they went for that I definitely would have done as you suggest.

Thing is, for the iOS icons, I'm really trying to key on the style of the default perspectives (Projects, Contexts, etc), rather than the icons Omni provides for custom perspectives, and as long as they're white in this mode, I'm hesitant to change them.

But, I don't know. I'll give this some further thought. Thanks for the feedback!

**Comment by deaghean** [comment]
Yeah, ok, I'm on it! ;)

**Comment by papernapkinhead** [comment]
Heh :-) I thought that build had already made it out on TestFlight. Thank you!!

**Comment by deaghean** [comment]
It'll take a little bit of time to go through these (my build process will need a bit of revision), but I did at least update the Retina versions of the icons in your screenshot:

- [Car](https://github.com/deaghean/omnifocus-perspective-icons/blob/dark-palette-support/dist/car/icon-ios-teal%402x.png)
- [Home](https://github.com/deaghean/omnifocus-perspective-icons/blob/dark-palette-support/dist/home/icon-ios-teal%402x.png)
- [Skull](https://github.com/deaghean/omnifocus-perspective-icons/blob/dark-palette-support/dist/skull/icon-ios-teal%402x.png)

If there are others you'd like me to prioritize, let me know.

**Comment by papernapkinhead** [comment]
Wow—thanks for the speedy response! These look fantastic—really great work. Guess I should get back to my "Bugs" perspective now...
